name: Django Audit

on:
  workflow_call: {}

jobs:
  test:
    name: "Tests + type-check"
    runs-on: ubuntu-latest
    steps:
      # --- initial setup ---
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: "3.10"
      - run: poetry install --no-interaction
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

        # --- type check ---
      - uses: jakebailey/pyright-action@v2

        # --- validate templates ---
      - name: Template validation
        run: |
          python manage.py validate_templates

        # --- unit tests and coverage ---
      - name: Unit tests
        run: |
          python manage.py migrate
          coverage run manage.py test --shuffle 1337
          coverage lcov -o coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

  style:
    name: "Style check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Fail if CRLF endings detected
        uses: erclu/check-crlf@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade djlint toml ruff codespell
      - name: Run ruff
        run: |
          ruff check --output-format=github $(git ls-files '*.py')
          ruff format --diff $(git ls-files '*.py')
      - name: Run djlint
        run: |
          djlint --check $(git ls-files '**/templates/**.html')
      - name: Run spell-check
        run: |
          codespell $(git ls-files)

  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--check **/*.{css,js,md}"
          dry: true
